export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGOUT = "LOGOUT";
export const TOGGLE_CART_HIDDEN = "TOGGLE_CART_HIDDEN";
export const ADD_ITEM = "ADD_ITEM";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
<<<<<<< HEAD
export const SAVE_ITEM_DB = "SAVE_ITEM_DB";
=======
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";

export const LOAD_SECTIONS = "LOAD_SECTIONS";
export const LOAD_SECTIONS_FAIL = "LOAD_SECTIONS_FAIL";


>>>>>>> 52872a5449644b19a594043008ea4464881a9292
